name: Deploy to Robot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 192.168.43.146
          REMOTE_USER: pi
          REMOTE_PORT: 22
          SCRIPT_BEFORE: |
            cd ~/Desktop
            mkdir test
          SOURCE: '.'
          TARGET: ~/Desktop/test/
